from tf import *
from db import *
from gd import * 
from datetime import datetime
import subprocess



querys_ctls_activos = {
    "SIAG" : """
    WITH CLIENTES_ACTIVOS AS (
	SELECT * 
	FROM ( 
    	SELECT INTER_CLAVE, CLAVE CLAVE_GARANTIA, FUNFAC_CLAVE, MONTO_CREDITO,  IMPORTE_DISPOSICION, PLAZO, 
    	GRACIA, TASA_INTERES, PORCENTAJE_GARANTIZADO, MONTO_GARANTIZADO, PORCENTAJE_COMISION, CVE_CARTERA, CVE_PORTAFOLIO 
    	FROM GIA.GIA_GARANTIAS 
    	WHERE ESTATUS_GARANTIA IS NULL OR ESTATUS_GARANTIA = 'R' AND (FECHA_VENCIMIENTO IS NULL)
		) RESULTADO
	INNER JOIN GIA.GIA_INTERMEDIARIOS INT ON RESULTADO.INTER_CLAVE = INT.CLAVE
	), PARTITION_CLTS AS (
	        SELECT 
	            CA.*, 
	            ROW_NUMBER() OVER (PARTITION BY CA.CLAVE ORDER BY CA.CLAVE) AS RN
	        FROM 
	            CLIENTES_ACTIVOS CA
	), CLIENTES_UNICOS AS (
		SELECT * 
		FROM PARTITION_CLTS 
		WHERE RN = 1
	),  INTERMEDIARIO_TELEFONO AS (
		SELECT 
	    INTER_CLAVE, 
	    LISTAGG(TELEFONO, ' -- ') WITHIN GROUP (ORDER BY TELEFONO) AS TELEFONOS
		FROM 
		    GIA.GIA_FUNCIONARIOS_FACULTADOS
		GROUP BY 
	    	INTER_CLAVE
	), CLT_UNICOS_TEL AS (
		SELECT CU.*, IT.TELEFONOS
		FROM CLIENTES_UNICOS CU
		LEFT JOIN INTERMEDIARIO_TELEFONO IT ON IT.INTER_CLAVE =  CU.CLAVE
	) SELECT  '' NEGOCIO, 
	    	DESCRIPCION NOMBRE_O_RAZON_SOCIAL,
	    	CLAVE NUMERO_CLIENTE, 
	    	'VIGENTE' ESTATUS, 
	    	'' NUMERO_CONTRATO,
	    	'N/A' GENERO,  
	    	'' FECHA_NAC_O_CONST, 
	    	'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
	    	'' PAIS_DE_NACIMIENTO, 
	    	'' NACIONALIDAD,
	    	'' PROFESION,
	    	'' CALLE,
	    	'' NUMERO_EXTERIOR, 
	    	'' NUMERO_INTERIOR, 
	    	'' COLONIA_URBANIZACION, 
	    	'' DELEGACION_MUNICIPIO, 
	    	'' CIUDAD_POBLACION, 
	    	'' ENTIDAD_FEDERATIVA, 
	    	'' CODIGO_POSTAL, 
	    	'' PAIS,
	    	TELEFONOS TELEFONO, 
	    	'' CORREO_ELECTRONICO, 
	    	CLAVE_INTERMEDIARIO_SIFC RFC, 
	    	'' CURP, 
	    	'' FIEL,
	    	'' REPRESENTANTE_LEGAL,
	    	TIPO_FINANCIERA TIPO_PERSONA, 
	    	'' PRODUCTO_CONTRATADO, 
	    	'SIAG' SISTEMA_ORIGEN
	FROM CLT_UNICOS_TEL
 	ORDER BY NOMBRE_O_RAZON_SOCIAL 
    """,  
    
    "SOI"  : """ 
    WITH CLIENTES AS (
        SELECT sb.*, sp.PAPAIS
        FROM SOI.SOI_BANCO sb
        INNER JOIN SOI_PAIS sp ON sp.PACVE_PAIS = sb.BACVE_PAIS
        WHERE BA_ACTIVO = 'S'
    ), CLIENTES_SOI_PLAZA AS (
        SELECT clt.*, sp.*
        FROM SOI.SOI_PLAZA sp
        RIGHT JOIN CLIENTES clt ON sp.PLCVE_BANC = clt.BACVE_BANC
    ), CLIENTES_AGRUPADOS AS (
    	SELECT 
    	    BACVE_BANC, 
    	    BANOM_BAN, 
    	    BACVE_PAIS, 
    	    BATIP_BANC, 
    	    BANACIONAL, 
    	    BA_ACTIVO, 
    	    PAPAIS,
    	    LISTAGG(PLPLAZA, ' -- ') WITHIN GROUP (ORDER BY PLPLAZA) AS PLPLAZA,
    	    LISTAGG(PLCVE_PAIS, ' -- ') WITHIN GROUP (ORDER BY PLCVE_PAIS) AS PLCVE_PAIS,
    	    LISTAGG(PLRFC, ' -- ') WITHIN GROUP (ORDER BY PLRFC) AS PLRFC,
    	    LISTAGG(PLDOM_CALLE, ' -- ') WITHIN GROUP (ORDER BY PLDOM_CALLE) AS PLDOM_CALLE,
    	    LISTAGG(PLDOM_NUMERO, ' -- ') WITHIN GROUP (ORDER BY PLDOM_NUMERO) AS PLDOM_NUMERO,
    	    LISTAGG(PLDOM_CIUDAD, ' -- ') WITHIN GROUP (ORDER BY PLDOM_CIUDAD) AS PLDOM_CIUDAD,
    	    LISTAGG(PLDOM_ESTADO, ' -- ') WITHIN GROUP (ORDER BY PLDOM_ESTADO) AS PLDOM_ESTADO,
    	    LISTAGG(PLDOM_CP, ' -- ') WITHIN GROUP (ORDER BY PLDOM_CP) AS PLDOM_CP,
    	    LISTAGG(PL_ACTIVO, ' -- ') WITHIN GROUP (ORDER BY PL_ACTIVO) AS PL_ACTIVO
    	FROM CLIENTES_SOI_PLAZA
    	WHERE PL_ACTIVO = 'S' OR PL_ACTIVO IS NULL OR BANOM_BAN = 'AMSTERDAM-ROTTERDAM BANK.'
    	GROUP BY BACVE_BANC, BANOM_BAN, BACVE_PAIS, BATIP_BANC, BANACIONAL, BA_ACTIVO, PAPAIS
    ) SELECT '' NEGOCIO, BANOM_BAN NOMBRE_O_RAZON_SOCIAL,  BACVE_BANC NUMERO_CLIENTE, 'VIGENTE' ESTATUS, '' NUMERO_CONTRATO, 
    'N/A' GENERO, '' FECHA_NAC_O_CONST,  '' ENTIDAD_FEDERATIVA_NACIMIENTO, '' PAIS_DE_NACIMIENTO, 
     BANOM_BAN NACIONALIDAD, '' PROFESION, PLDOM_CALLE CALLE, PLDOM_NUMERO NUMERO_EXTERIOR, '' NUMERO_INTERIOR, '' COLONIA_URBANIZACION, 
     '' DELEGACION_MUNICIPIO, PLDOM_CIUDAD CIUDAD_POBLACION, PLDOM_ESTADO ENTIDAD_FEDERATIVA, PLDOM_CP CODIGO_POSTAL, PAPAIS PAIS, '' TELEFONO,
     '' CORREO_ELECTRONICO, PLRFC RFC, '' CURP, '' FIEL, '' REPRESENTANTE_LEGAL, 'PM' TIPO_PERSONA, 'SOI' SISTEMA_ORIGEN, '' PRODUCTO_CONTRATADO
     FROM CLIENTES_AGRUPADOS
     ORDER BY NOMBRE_O_RAZON_SOCIAL 
    """,
    
    "MECA" : """
    WITH ClientesVig AS (
        SELECT *
        FROM MECA.CAPF_CLIENTES 
        WHERE CLI_EST_CLAVE = 'VIG' AND CLI_NOMBRE != '0' AND CLI_NOMBRE NOT LIKE 'BAJA'
    ),
    ClientesPorArea AS (
        SELECT LISTAGG(ca.ARE_DESCRIPCION, ', ') WITHIN GROUP (ORDER BY ca.ARE_DESCRIPCION) AS descripciones, 
               ccpa.CAR_CLI_CLAVE
        FROM MECA.CAPF_CLIENTES_POR_AREA ccpa
        INNER JOIN MECA.CAPF_AREAS ca ON ccpa.CAR_ARE_CLAVE = ca.ARE_CLAVE
        GROUP BY ccpa.CAR_CLI_CLAVE
    ),
    ClientesConDescripcion AS (
        SELECT r1.descripciones, cc.*
        FROM ClientesVig cc
        LEFT JOIN ClientesPorArea r1 ON r1.CAR_CLI_CLAVE = cc.CLI_CLAVE
    ),
    ClientesConTipo AS (
        SELECT r2.*, tp.TDC_DESCRIPCION
        FROM ClientesConDescripcion r2
        INNER JOIN MECA.CAPF_TIPOS_DE_CLIENTES tp ON tp.TDC_CLAVE = r2.CLI_TDC_CLAVE
    ), CLIENTES_CON_EDO AS (
    	SELECT CCTI.*, CE.EDO_DESCRIPCION
    	FROM ClientesConTipo CCTI
    	LEFT JOIN MECA.CAPF_ESTADOS CE ON (CCTI.CLI_EDO_PAI_CLAVE = CE.EDO_PAI_CLAVE) AND (CCTI.CLI_EDO_CLAVE = CE.EDO_CLAVE)
    ), CLIENTES_CON_PAIS AS (
    	SELECT CCED.*, CAPA.PAI_DESCRIPCION
    	FROM CLIENTES_CON_EDO CCED
    	LEFT JOIN MECA.CAPF_PAISES CAPA ON CCED.CLI_EDO_PAI_CLAVE = CAPA.PAI_CLAVE
    ) SELECT 
    	DESCRIPCIONES NEGOCIO, 
    		 CLI_NOMBRE NOMBRE_O_RAZON_SOCIAL,
    		 CLI_CLAVE NUMERO_CLIENTE, 
    		'VIGENTE' ESTATUS, 
    		'' NUMERO_CONTRATO,
    		'' GENERO,  
    		'' FECHA_NAC_O_CONST, 
    		'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
    		'' PAIS_DE_NACIMIENTO, 
    		CLI_NACIONALIDAD NACIONALIDAD,
    		'' PROFESION,
    		CLI_DIRECCION CALLE,
    		'' NUMERO_EXTERIOR, 
    		'' NUMERO_INTERIOR, 
    		'' COLONIA_URBANIZACION, 
    		'' DELEGACION_MUNICIPIO, 
    		'' CIUDAD_POBLACION, 
    		EDO_DESCRIPCION ENTIDAD_FEDERATIVA, 
    		'' CODIGO_POSTAL, 
    		PAI_DESCRIPCION PAIS,
    		CLI_TELEFONO TELEFONO, 
    		'' CORREO_ELECTRONICO, 
    		'' RFC,
    		CLI_RFC_LETRAS, CLI_RFC_FECHA, CLI_RFC_HOMO,
    		'' CURP, 
    		'' FIEL,
    		'' REPRESENTANTE_LEGAL,
    		'PM' TIPO_PERSONA, 
    		TDC_DESCRIPCION TIPO_DE_CLIENTE,
    		'' PRODUCTO_CONTRATADO,
    		'MECA' SISTEMA_ORIGEN
    FROM CLIENTES_CON_PAIS
    ORDER BY NOMBRE_O_RAZON_SOCIAL  
    """,
    
    "SIPE":""" 
    WITH BAN_ACT_DIR AS (
    	SELECT * 
    	FROM SIPE.SIPE_BANCOS sp
    	LEFT JOIN SIPE.SIPE_SUCURSALES_BANCO ssb ON ssb.SUC_BCO_CLAVE= sp.BCO_CLAVE
    	WHERE SP.BCO_ESTATUS = 'A'
    	ORDER BY BCO_CLAVE
    ), TEL_AGRUPADO AS (
    	SELECT 
    	    CTO_SUC_NUMERO,
    	    RTRIM(XMLAGG(XMLELEMENT(e, CTO_TELEFONO || ' -- ').EXTRACT('//text()') ORDER BY CTO_TELEFONO).GetClobVal(), ' -- ') AS CTO_TELEFONOS
    	FROM 
    	    SIPE.SIPE_CONTACTOS sc
    	GROUP BY 
    	    CTO_SUC_NUMERO
    ), BAN_ACT_TEL AS (
    	SELECT BAD.*, TA.CTO_TELEFONOS
    	FROM BAN_ACT_DIR BAD
    	LEFT JOIN TEL_AGRUPADO TA ON BAD.SUC_NUMERO= TA.CTO_SUC_NUMERO
    ),  BAN_CIU AS( 
    	SELECT BAT.*, SC.CDS_NOMBRE
    	FROM BAN_ACT_TEL BAT
    	LEFT JOIN SIPE.SIPE_CIUDADES SC ON (BAT.SUC_CDS_CLAVE = SC.CDS_CLAVE) AND (BAT.SUC_PAI_CLAVE = SC.CDS_PAI_CLAVE) AND (BAT.SUC_EDO_CLAVE = SC.CDS_EDO_CLAVE) 
    ), BAN_EDO AS (
    	SELECT BC.*, SE.EDO_NOMBRE
    	FROM BAN_CIU BC
    	LEFT JOIN SIPE.SIPE_ESTADOS SE ON (BC.SUC_EDO_CLAVE = SE.EDO_CLAVE) AND (BC.SUC_PAI_CLAVE = SE.EDO_PAI_CLAVE)
    ), BAN_PAIS AS (
    	SELECT BE.*, SP.PAI_NOMBRE
    	FROM BAN_EDO BE
    	LEFT JOIN SIPE.SIPE_PAISES SP ON BE.SUC_PAI_CLAVE = SP.PAI_CLAVE
    ) SELECT '' NEGOCIO, 
    	BCO_NOMBRE NOMBRE_O_RAZON_SOCIAL,
    	BCO_CLAVE NUMERO_CLIENTE, 
    	'VIGENTE' ESTATUS, 
    	'' NUMERO_CONTRATO,
    	'N/A' GENERO,  
    	'' FECHA_NAC_O_CONST, 
    	'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
    	'' PAIS_DE_NACIMIENTO, 
    	'' NACIONALIDAD,
    	'' PROFESION,
    	SUC_DIRECCION CALLE,
    	'' NUMERO_EXTERIOR, 
    	'' NUMERO_INTERIOR, 
    	'' COLONIA_URBANIZACION, 
    	'' DELEGACION_MUNICIPIO, 
    	CDS_NOMBRE CIUDAD_POBLACION, 
    	EDO_NOMBRE ENTIDAD_FEDERATIVA, 
    	'' CODIGO_POSTAL, 
    	PAI_NOMBRE PAIS,
    	CTO_TELEFONOS TELEFONO, 
    	'' CORREO_ELECTRONICO, 
    	SUC_RFC RFC, 
    	'N/A' CURP, 
    	'' FIEL,
    	'' REPRESENTANTE_LEGAL,
    	'PM' TIPO_PERSONA, 
    	'' PRODUCTO_CONTRATADO, 
    	'SIPE' SISTEMA_ORIGEN 
    FROM BAN_PAIS
    ORDER BY NOMBRE_O_RAZON_SOCIAL 
    """,
    
    "SIMS" : """
    WITH CLIENTES_ACTIVOS AS (
    SELECT *
    	FROM SIMS.SIMS_CONTRAPARTES 
    	WHERE NOMBRE NOT LIKE '%INACTI%' AND NOMBRE NOT LIKE '%APLICA%'
    ), CLTS_PAISES AS(
    	SELECT CA.*, sp.NOMBRE PAIS
    	FROM CLIENTES_ACTIVOS CA 
    	LEFT JOIN SIMS.SIMS_PAISES sp ON CA.CVE_PAIS = sp.CLAVE
    ), CLTS_CIUDADES AS (
    	SELECT CTP.*, SC.NOMBRE CIUDAD
    	FROM CLTS_PAISES CTP 
    	LEFT JOIN SIMS.SIMS_CIUDADES SC ON CTP.CVE_CIUDAD = SC.CLAVE
    ) SELECT 
    	'' NEGOCIO, 
    	NOMBRE NOMBRE_O_RAZON_SOCIAL,
    	CLAVE NUMERO_CLIENTE, 
    	'VIGENTE' ESTATUS, 
    	'' NUMERO_CONTRATO,
    	'N/A' GENERO,  
    	'' FECHA_NAC_O_CONST, 
    	'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
    	'' PAIS_DE_NACIMIENTO, 
    	'' NACIONALIDAD,
    	'' PROFESION,
    	DIRECCION CALLE,
    	'' NUMERO_EXTERIOR, 
    	'' NUMERO_INTERIOR, 
    	'' COLONIA_URBANIZACION, 
    	'' DELEGACION_MUNICIPIO, 
    	CIUDAD CIUDAD_POBLACION, 
    	CVE_CIUDAD, 
    	'' ENTIDAD_FEDERATIVA, 
    	'' CODIGO_POSTAL, 
    	PAIS,
    	TELEFONO, 
    	FAX CORREO_ELECTRONICO, 
    	'' RFC, 
    	'' CURP, 
    	'' FIEL,
    	'' REPRESENTANTE_LEGAL,
    	'PM' TIPO_PERSONA, 
    	'' PRODUCTO_CONTRATADO, 
    	'SIMS' SISTEMA_ORIGEN
    FROM CLTS_CIUDADES
    ORDER BY NOMBRE_O_RAZON_SOCIAL 
    """, 
 
    "TAS"  : """
    WITH CLIENTES_ACTIVOS AS(
    	SELECT * 
        FROM TAS.CLIENTE cl
        WHERE cl.FBAJA IS NULL
    ), 
    CLIENTES_CON_NA AS(
    	SELECT CA.*, FN.NNACIONALIDAD NACIONALIDAD
    	FROM CLIENTES_ACTIVOS CA
    	INNER JOIN TAS.FNACIONALIDAD FN ON CA.INACIONALIDAD = FN.INACIONALIDAD
    ),
    CLIENTES_CON_TIP_INV AS (
    	SELECT CCN.*, tp.DESCRIP TIPO_DE_PERSONA
    	FROM CLIENTES_CON_NA CCN
    	LEFT JOIN TAS.TIPINVER tp ON CCN.TIPINVE = tp.TIPINVE
    ) SELECT
    	'' NEGOCIO, 
    	'' NOMBRE_O_RAZON_SOCIAL,
    	"U##NOMBRE" , NOMBRE, NOMLARGO,
    	CUENTA NUMERO_CLIENTE, 
    	'VIGENTE' ESTATUS, 
    	'' NUMERO_CONTRATO,
    	'' GENERO,  
    	'' FECHA_NAC_O_CONST, 
    	'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
    	'' PAIS_DE_NACIMIENTO, 
    	NACIONALIDAD,
    	IACTIV_ECONO PROFESION,
    	'' CALLE,
    	'' NUMERO_EXTERIOR, 
    	'' NUMERO_INTERIOR, 
    	'' COLONIA_URBANIZACION, 
    	'' DELEGACION_MUNICIPIO, 
    	'' CIUDAD_POBLACION,  
    	'' ENTIDAD_FEDERATIVA, 
    	'' CODIGO_POSTAL, 
    	IREGIONAL PAIS,
    	'' TELEFONO, 
    	TELEFONO1 , TELEFONO2,
    	EMAIL CORREO_ELECTRONICO, 
    	RFC RFC, 
    	'' CURP, 
    	'' FIEL,
    	'' REPRESENTANTE_LEGAL,
    	TIPO_DE_PERSONA TIPO_PERSONA, 
    	'' PRODUCTO_CONTRATADO, 
    	'TAS' SISTEMA_ORIGEN
    FROM CLIENTES_CON_TIP_INV
    ORDER BY NOMBRE_O_RAZON_SOCIAL 
    """,
    
    "SIRAC" : """
   WITH CLT_ACT_X_CONTRATO AS (
		SELECT cxc.CODIGO_CLIENTE, cxc.NUMERO_CONTRATO, c.FECHA_APERTURA, c.FECHA_VENCIMIENTO, c.MONTO_APROBADO, c.MONTO_DISPONIBLE, c.CODIGO_EMPRESA,
        	c.CODIGO_LINEA_FINANCIERA, c.OBSERVACIONES OB1, c.TIPO_CONTRATO, c.ESTADO_CONTRATO, c.CODIGO_SUB_APLICACION, c.CODIGO_APLICACION
            FROM SIRAC.PR_CONTRATOS_X_CLIENTE cxc
            INNER JOIN SIRAC.PR_CONTRATOS c ON cxc.NUMERO_CONTRATO = c.NUMERO_CONTRATO
            WHERE c.FECHA_VENCIMIENTO > SYSDATE AND ESTADO_CONTRATO = 1 
        ),
        CLT_CONTRATO_PRESTAMOS AS (
        	SELECT CALF.*, PP.NUMERO_PRESTAMO, PP.CODIGO_ESTADO_CARTERA, PP.ESTADO
        	FROM CLT_ACT_X_CONTRATO CALF
        	LEFT JOIN SIRAC.PR_PRESTAMOS PP ON CALF.CODIGO_CLIENTE = PP.CODIGO_CLIENTE AND CALF.NUMERO_CONTRATO = PP.NUMERO_CONTRATO
        ), 
        CLTS_ACTIVOS_FILTRO_2 AS(
        	SELECT DISTINCT(CODIGO_CLIENTE) CODIGO_CLIENTE_UNICO FROM CLT_CONTRATO_PRESTAMOS WHERE ESTADO = 1 OR ESTADO = 10 OR ESTADO IS NULL
        ), 
        CLIENTES_ACTIVOS AS (
    	SELECT MG.*
    	FROM CLTS_ACTIVOS_FILTRO_2 CAF2
    	INNER JOIN SIRAC.MG_CLIENTES MG ON MG.CODIGO_CLIENTE = CAF2.CODIGO_CLIENTE_UNICO
   	 	), 
   	 	CLIENTES_ACTIVOS_PAIS AS (
    	SELECT CIXC.*, x.NOMBRE PAIS
    	FROM CLIENTES_ACTIVOS CIXC
    	LEFT JOIN SIRAC.MG_PAISES x ON CIXC.CODIGO_PAIS = x.CODIGO_PAIS
    	), 
    	CLIENTE_ACTIVOS_DELEGACION AS (
    	SELECT CIP.*, MM.NOMBRE DELEGACION_MUNICIPIO      
    	FROM CLIENTES_ACTIVOS_PAIS CIP
    	LEFT JOIN SIRAC.MG_MUNICIPIOS MM ON  MM.CODIGO_PAIS = CIP.CODIGO_PAIS AND MM.CODIGO_DEPARTAMENTO = CIP.CODIGO_DEPARTAMENTO AND MM.CODIGO_MUNICIPIO = CIP.CODIGO_MUNICIPIO
    	), 
    	CLIENTES_ACTIVOS_ENT_FED AS (
        SELECT 
            CIM.*, MD.NOMBRE AS ENTIDAD_FEDERATIVA     
        FROM CLIENTE_ACTIVOS_DELEGACION CIM
        LEFT JOIN SIRAC.MG_DEPARTAMENTOS MD ON  MD.CODIGO_PAIS = CIM.CODIGO_PAIS AND MD.CODIGO_DEPARTAMENTO = CIM.CODIGO_DEPARTAMENTO
    	), CLIENTES_ACTIVOS_PAIS_NAC AS (
    	SELECT CU.*, MGP.NOMBRE DESC_PAIS_NACIMIENTO, MGP.NACIONALIDAD
    	FROM CLIENTES_ACTIVOS_ENT_FED CU
    	LEFT JOIN SIRAC.MG_PAISES MGP ON CU.PAIS_NACIMIENTO = MGP.CODIGO_PAIS
    ), TAB_FINAL AS (
    SELECT 
     	'' NEGOCIO, 
    	'' NOMBRE_O_RAZON_SOCIAL,
    	CODIGO_CLIENTE NUMERO_CLIENTE,
    	NOMBRES, 
    	PRIMER_APELLIDO, 
    	SEGUNDO_APELLIDO, 
    	RAZON_SOCIAL, 
    	NOMBRE_COMERCIAL,
    	'VIGENTE' ESTATUS, 
    	'' NUMERO_CONTRATO,	
    	SEXO GENERO,  
    	FECHA_DE_NACIMIENTO FECHA_NAC_O_CONST, 
    	'' ENTIDAD_FEDERATIVA_NACIMIENTO, 
    	DESC_PAIS_NACIMIENTO PAIS_DE_NACIMIENTO, 
    	NACIONALIDAD NACIONALIDAD,
    	CODIGO_PROFESION PROFESION,
    	'' CALLE,
    	'' NUMERO_EXTERIOR, 
    	'' NUMERO_INTERIOR, 
    	'' COLONIA_URBANIZACION, 
    	DELEGACION_MUNICIPIO, 
    	'' CIUDAD_POBLACION, 
    	ENTIDAD_FEDERATIVA ENTIDAD_FEDERATIVA, 
    	'' CODIGO_POSTAL, 
    	PAIS,
    	'' TELEFONO, 
    	'' CORREO_ELECTRONICO, 
    	NUMERO_IDENTIFICACION RFC, 
    	RFC_GEN,
    	CURP, 
    	FIEL,
    	REPRESENTANTE_LEGAL,
    	CODIGO_TIPO_IDENTIFICACION TIPO_PERSONA,
    	'SIRAC' SISTEMA_ORIGEN,
		'' PRODUCTO_CONTRATADO, 
    	 TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'YYYY-MM-DD') FECHA_CONSULTA
    FROM CLIENTES_ACTIVOS_PAIS_NAC
    ORDER BY CODIGO_CLIENTE
    ) SELECT * FROM TAB_FINAL
    """,  
}


list_dbs_clt_activos = [db_siag, db_soi, db_meca, db_sims, db_sipe, db_tas, db_sirac]
path_exit = "/home/ale1726/proyects/datalake/clientes/data/clientes_activos"
path_logs = "/home/ale1726/proyects/datalake/clientes/data/logs"

date_now = datetime.now().strftime("%d_%m_%Y") 

repositorio_data_clt =  os.path.join(path_exit,date_now)

os.makedirs(repositorio_data_clt, exist_ok=True)

for database in list_dbs_clt_activos:
    try:
       print(database["NAME"])
       get_table(path_exit = repositorio_data_clt  , db = database, name_archivo = f"Clientes_activos_{database['NAME']}" , query  = querys_ctls_activos[database["NAME"]])  
    except Exception as error:
        repositorio_log = os.path.join(path_logs, date_now)
        os.makedirs(repositorio_log, exist_ok=True)
        log_file =  os.path.join(repositorio_log,f"errors_clts_{database['NAME']}_{date_now}.log")
        with open(log_file, 'a') as archivo:
            archivo.write(str(error))
            
subprocess.run([
        "python",
        "/home/ale1726/proyects/datalake/clientes/clientes_eda/utils/pipeline_ETL.py",
        repositorio_data_clt
    ])