
from tf import *
from db import *
from gd import * 
from datetime import datetime
import pandas as pd
from sqlalchemy import create_engine

sistema = ""
querys_productos ={
    "SIAG": """
    WITH CLIENTES_ACTIVOS AS (
		SELECT RESULTADO.*, INT.DESCRIPCION AS CLIENTE, INT.DESC_CORTA  
			FROM ( 
		    	SELECT *
		    	FROM GIA.GIA_GARANTIAS 
		    	WHERE ESTATUS_GARANTIA IS NULL OR ESTATUS_GARANTIA = 'R' AND (FECHA_VENCIMIENTO IS NULL)
				) RESULTADO
			INNER JOIN GIA.GIA_INTERMEDIARIOS INT ON RESULTADO.INTER_CLAVE = INT.CLAVE
		), CON_SUBPRODUCTOS AS(
			SELECT CA.*, SP.DESCRIPCION AS SUBPRODUCTO
			FROM CLIENTES_ACTIVOS CA
			LEFT JOIN GIA.SIAG_PORTAFOLIOS SP ON CA.CVE_CARTERA = SP.CVE_CARTERA AND CA.CVE_PORTAFOLIO = SP.CVE_PORTAFOLIO 
		), INFORMACION_GARANTIA AS (
			SELECT 
			CLAVE NUMERO_DE_GARANTIA,
			INTER_CLAVE NUMERO_CLIENTE,
			CLIENTE,
			DESC_CORTA,
			SUBPRODUCTO,
			FECHA_REGISTRO_GARANTIA,
			MONTO_CREDITO,
			PORCENTAJE_GARANTIZADO,
			MONTO_GARANTIZADO,
			TASA_INTERES,
			PORCENTAJE_COMISION,
			ROUND(MONTO_CREDITO * (PORCENTAJE_COMISION/100)) GANANCIA,
			EXTRACT(YEAR FROM FECHA_REGISTRO_GARANTIA) AIO,
			EXTRACT(MONTH FROM FECHA_REGISTRO_GARANTIA) MES,
			EXTRACT(DAY FROM FECHA_REGISTRO_GARANTIA) DIA
		  FROM CON_SUBPRODUCTOS
		) SELECT * FROM INFORMACION_GARANTIA
    """, 
    "SIRAC": """
        WITH CLT_ACT_X_CONTRATO AS (
        	SELECT cxc.CODIGO_CLIENTE, cxc.NUMERO_CONTRATO, c.FECHA_APERTURA, c.FECHA_VENCIMIENTO, c.MONTO_APROBADO, c.MONTO_DISPONIBLE, c.CODIGO_EMPRESA,
        	c.CODIGO_LINEA_FINANCIERA, c.OBSERVACIONES OB1, c.TIPO_CONTRATO, c.ESTADO_CONTRATO, c.CODIGO_SUB_APLICACION, c.CODIGO_APLICACION
            FROM SIRAC.PR_CONTRATOS_X_CLIENTE cxc
            INNER JOIN SIRAC.PR_CONTRATOS c ON cxc.NUMERO_CONTRATO = c.NUMERO_CONTRATO
            WHERE c.FECHA_VENCIMIENTO > SYSDATE AND ESTADO_CONTRATO = 1 
        ),  CLTS_ACT_LINEA_FINACIERA AS (
        	SELECT CAXC.*, LF.DESCRIPCION AS DESC_LINEA_FINANCIERA
        	FROM CLT_ACT_X_CONTRATO  CAXC
        	LEFT JOIN SIRAC.MG_LINEA_FINANCIERAS LF ON CAXC.CODIGO_LINEA_FINANCIERA = LF.CODIGO_LINEA_FINANCIERA AND CAXC.CODIGO_EMPRESA = LF.CODIGO_EMPRESA
        ), CLT_CONTRATO_PRESTAMOS AS (
        	SELECT CALF.*, PP.NUMERO_PRESTAMO, PP.CODIGO_ESTADO_CARTERA, PP.ESTADO, PP.CODIGO_TIPO_AMORTIZACION, PP.MONTO_INICIAL, 
        	PP.VALOR_CUOTA, PP.TIPO_TASA, PP.TASA_TOTAL, PP.PLAZO, PP.NUMERO_CUOTAS, PP.COMISION, PP.CANTIDAD_CUOTAS_PAGADAS
        	FROM CLTS_ACT_LINEA_FINACIERA CALF
        	LEFT JOIN SIRAC.PR_PRESTAMOS PP ON CALF.CODIGO_CLIENTE = PP.CODIGO_CLIENTE AND CALF.NUMERO_CONTRATO = PP.NUMERO_CONTRATO
        ), CLTS_ACTIVOS_FILTRO_2 AS(
        	SELECT * FROM CLT_CONTRATO_PRESTAMOS WHERE ESTADO = 1 OR ESTADO = 10 OR ESTADO IS NULL
        ), CLT_SUP_APLICACION AS (
        	SELECT CAF2.*, MGSA.DESCRIPCION PRODUCTO, MGSA.CODIGO_MONEDA
        	FROM CLTS_ACTIVOS_FILTRO_2 CAF2
        	LEFT JOIN SIRAC.MG_SUB_APLICACIONES MGSA ON CAF2.CODIGO_APLICACION = MGSA.CODIGO_APLICACION AND CAF2.CODIGO_SUB_APLICACION = MGSA.CODIGO_SUB_APLICACION
        ), CLT_TIPOS_AMORTIZACION AS (
        	SELECT CSA.*, PRTA.DESCRIPCION AS AMORTIZACION 
        	FROM CLT_SUP_APLICACION CSA
        	LEFT JOIN SIRAC.PR_TIPOS_AMORTIZACION PRTA ON CSA.CODIGO_TIPO_AMORTIZACION = PRTA.CODIGO_TIPO_AMORTIZACION
        ), CLT_INFO_X_CONTRATO AS (
        	SELECT CTTAM.*, MG.CODIGO_TIPO_IDENTIFICACION, MG.CODIGO_PAIS, NOMBRES,
        	PRIMER_APELLIDO,SEGUNDO_APELLIDO,SEXO,FECHA_DE_NACIMIENTO,
        	RAZON_SOCIAL,NOMBRE_COMERCIAL,ESTATUTO,CODIGO_DEPARTAMENTO,
        	CODIGO_MUNICIPIO,NO_EMPLEADOS,VENTAS_NETAS,CODIGO_SECTOR,
        	CODIGO_SUBSECTOR,CODIGO_RAMA,CODIGO_CLASE,PAIS_NACIMIENTO
        	FROM CLT_TIPOS_AMORTIZACION CTTAM
        	LEFT JOIN SIRAC.MG_CLIENTES MG ON MG.CODIGO_CLIENTE = CTTAM.CODIGO_CLIENTE
        ), CLT_INFO_P AS (
        	SELECT CIXC.*, x.NOMBRE PAIS, x.NACIONALIDAD
        	FROM CLT_INFO_X_CONTRATO CIXC
        	LEFT JOIN SIRAC.MG_PAISES x ON CIXC.CODIGO_PAIS = x.CODIGO_PAIS
        ), CLT_INFO_MUN AS (
        	SELECT CIP.*, MM.NOMBRE DELEGACION_MUNICIPIO      
        	FROM CLT_INFO_P CIP
        	LEFT JOIN SIRAC.MG_MUNICIPIOS MM ON  MM.CODIGO_PAIS = CIP.CODIGO_PAIS AND MM.CODIGO_DEPARTAMENTO = CIP.CODIGO_DEPARTAMENTO AND MM.CODIGO_MUNICIPIO = CIP.CODIGO_MUNICIPIO
        ), CLT_INFO_ENT_FED AS (
            SELECT 
                CIM.*, MD.NOMBRE AS ENTIDAD_FEDERATIVA     
            FROM CLT_INFO_MUN CIM
            LEFT JOIN SIRAC.MG_DEPARTAMENTOS MD ON  MD.CODIGO_PAIS = CIM.CODIGO_PAIS AND MD.CODIGO_DEPARTAMENTO = CIM.CODIGO_DEPARTAMENTO
        ), CLT_INF_SECTOR AS(
        	SELECT CIEF.*, MTS.DESCRIPCION TIPO_SECTOR
        	FROM CLT_INFO_ENT_FED CIEF
        	LEFT JOIN SIRAC.MG_TIPO_SECTOR MTS ON CIEF.CODIGO_SECTOR =  MTS.CODIGO_SECTOR
        ), CLT_INF_SUBSECTOR AS(
        	SELECT CISEC.*, MTSC.DESCRIPCION TIPO_SUBSECTOR
        	FROM CLT_INF_SECTOR CISEC
        	LEFT JOIN SIRAC.MG_TIPO_SUBSECTOR MTSC ON CISEC.CODIGO_SECTOR = MTSC.CODIGO_SECTOR AND CISEC.CODIGO_SUBSECTOR = MTSC.CODIGO_SUBSECTOR
        ), CLT_INF_RAMA AS (
        	SELECT CISECS.*, MTR.DESCRIPCION TIPO_RAMA
        	FROM CLT_INF_SUBSECTOR CISECS
        	LEFT JOIN SIRAC.MG_TIPO_RAMA MTR ON 
        	CISECS.CODIGO_SECTOR = MTR.CODIGO_SECTOR AND CISECS.CODIGO_SUBSECTOR = MTR.CODIGO_SUBSECTOR  
        	AND CISECS.CODIGO_RAMA = MTR.CODIGO_RAMA
        ), CLT_INF_CLASE AS (
        	SELECT CIRA.*, MTC.DESCRIPCION TIPO_CLASE
        	FROM CLT_INF_RAMA CIRA
        	LEFT JOIN SIRAC.MG_TIPO_CLASE MTC ON 
        	CIRA.CODIGO_SECTOR = MTC.CODIGO_SECTOR AND CIRA.CODIGO_SUBSECTOR = MTC.CODIGO_SUBSECTOR  
        	AND CIRA.CODIGO_RAMA = MTC.CODIGO_RAMA AND CIRA.CODIGO_CLASE = MTC.CODIGO_CLASE
        ), TAB_FINAL_CLIENTE_PROD AS (
        	SELECT
        	CODIGO_CLIENTE,
        	CODIGO_TIPO_IDENTIFICACION,
        	NOMBRES,
        	PRIMER_APELLIDO,
        	SEGUNDO_APELLIDO,
        	SEXO,
        	FECHA_DE_NACIMIENTO,
        	RAZON_SOCIAL,
        	NOMBRE_COMERCIAL,
        	NO_EMPLEADOS,
        	VENTAS_NETAS,
        	PAIS,
        	NACIONALIDAD,
        	DELEGACION_MUNICIPIO,
        	ENTIDAD_FEDERATIVA,
        	TIPO_SECTOR,
        	TIPO_SUBSECTOR,
        	TIPO_RAMA,
         	TIPO_CLASE,
        	NUMERO_CONTRATO,
        	NUMERO_PRESTAMO,
        	FECHA_APERTURA,
        	EXTRACT(YEAR FROM FECHA_APERTURA) "AÑO_REGISTRO",
        	EXTRACT(MONTH FROM FECHA_APERTURA) MES_REGISTRO,
        	EXTRACT(DAY FROM FECHA_APERTURA) DIA_REGISTRO,
        	FECHA_VENCIMIENTO,
        	EXTRACT(YEAR FROM FECHA_VENCIMIENTO) "AÑO_VENCIMIENTO",
        	EXTRACT(MONTH FROM FECHA_VENCIMIENTO) MES_VENCIMIENTO,
        	EXTRACT(DAY FROM FECHA_VENCIMIENTO) DIA_VENCIMIENTO,
        	PRODUCTO,
        	DESC_LINEA_FINANCIERA,
        	CODIGO_MONEDA,
        	MONTO_APROBADO,
        	MONTO_DISPONIBLE,
        	MONTO_INICIAL,
        	TIPO_TASA,
        	TASA_TOTAL,
        	PLAZO,
        	CODIGO_TIPO_AMORTIZACION,
        	AMORTIZACION,
        	NUMERO_CUOTAS, 
        	VALOR_CUOTA,
        	CANTIDAD_CUOTAS_PAGADAS
        	FROM CLT_INF_CLASE
        	ORDER BY CODIGO_CLIENTE
        ) SELECT * FROM TAB_FINAL_CLIENTE_PROD
        """,
    "TAS": """
        WITH CLIENTES_ACTIVOS AS(
			SELECT CUENTA, ESPROVEED, TIPINVE, NLINEA, NOMBRE, NOMLARGO, RFC 
		    FROM TAS.CLIENTE cl
		    WHERE cl.FBAJA IS NULL
		), CLIENTES_ACT_TP AS (
			SELECT CA.*, TI.DESCRIP
			FROM CLIENTES_ACTIVOS CA
			LEFT JOIN TAS.TIPINVER TI ON TI.U##TIPINVE =  CA.TIPINVE
		), CLIENTES_OPERACIONES AS (
			SELECT CAT.*, 
			FO.ICONTRATO, FO.IORDEN, FO.FOPER, FO.FLIQ, FO.CPZO_DE, FO.CPZO_A, FO.FVENCE,  
			FO.IINSTR, FO.ITINSTR, FO.TASA, FO."U##ITAJUS",
			FO.MORDEN, FO.MASIG, FO.FECHA, FO.MREAL, FO.PLAZOREF
			FROM CLIENTES_ACT_TP CAT
			LEFT JOIN TAS.FORDEN FO ON FO.ICONTRATO = CAT.CUENTA
		), CLIENTES_OPERACIONES_INST AS (
			SELECT CO.*, FT.NTINSTR
			FROM CLIENTES_OPERACIONES CO
			LEFT JOIN TAS.FTINSTR FT ON FT."U##ITINSTR" = CO.ITINSTR 
		), TAB_FINAL AS ( 
			SELECT 
			CUENTA NUMERO_CLIENTE,
			ESPROVEED,
			DESCRIP TIPO_PERSONA, 
			NOMBRE, 
			NOMLARGO, 
			RFC, 
			NLINEA,
			ICONTRATO,
			IORDEN,
			FOPER,
			EXTRACT(YEAR FROM FOPER) "ANIO_OPE",
			EXTRACT(MONTH FROM FOPER) "MES_OPE",
			EXTRACT(DAY FROM FOPER) "DIA_OPE",
			FLIQ,
			EXTRACT(YEAR FROM FLIQ) "ANIO_FLIQ",
			EXTRACT(MONTH FROM FLIQ) "MES_FLIQ",
			EXTRACT(DAY FROM FLIQ) "DIA_FLIQ",
			CPZO_DE,
			CPZO_A,
			PLAZOREF,
			FVENCE,
			EXTRACT(YEAR FROM FVENCE) "ANIO_FVENCE",
			EXTRACT(MONTH FROM FVENCE) "MES_FVENCE",
			EXTRACT(DAY FROM FVENCE) "DIA_FVENCE",
			IINSTR,
			ITINSTR,
			NTINSTR,
			TASA,
			"U##ITAJUS" MONEDA,
			MORDEN MONTO_ORDEN,
			MASIG MONTO_ASIGNADO,
			MREAL MONTO_REAL,
			FECHA FECHA_REGISTRO
			FROM CLIENTES_OPERACIONES_INST 
			WHERE IORDEN IS NOT NULL
			) SELECT * FROM TAB_FINAL
		""",
	"MECA": """
		WITH CLIENTES_VIG AS (
		    SELECT CFCL.CLI_CLAVE_FFON, CFCL.CLI_CLAVE, CFCL.CLI_NOMBRE, CTDC.TDC_DESCRIPCION AS TIPO_CLIENTE
			FROM MECA.CAPF_CLIENTES CFCL
			LEFT JOIN MECA.CAPF_TIPOS_DE_CLIENTES CTDC ON CFCL.CLI_TDC_CLAVE = CTDC.TDC_CLAVE
			WHERE CFCL.CLI_EST_CLAVE = 'VIG' AND CFCL.CLI_NOMBRE != '0'
		), OPE_C1 AS (
			SELECT MO.*, MI.INS_DESCRIPCION INSTRUMENTO
			FROM MECA.MECA_OPERACIONES MO
			LEFT JOIN MECA.MECA_INSTRUMENTOS MI ON MO.OPE_INS_CLAVE = MI.INS_CLAVE
		), OPE_C2 AS (
			SELECT OP.*, CAT.TMO_DESCRIPCION TIPO_MOVIMIENTO
			FROM OPE_C1 OP
			LEFT JOIN MECA.MECA_TIPOS_MOVIMIENTO CAT ON OP.OPE_TMO_CLAVE = CAT.TMO_CLAVE
		), TAB_OPE AS(
			SELECT OPE_FOLIO, OPE_TYPE, OPE_INS_CLAVE ,INSTRUMENTO, OPE_SER_NUM_SERIE, OPE_SER_EMI_CLAVE, 
				OPE_TMO_CLAVE, TIPO_MOVIMIENTO, OPE_CLI_CLAVE, OPE_DIV_CLAVE_SWIFT, OPE_NUM_TITULOS, OPE_PRECIO_POSTURA
				OPE_IMPORTE_TITULOS, OPE_FECHA_PACTADA, OPE_FECHA_SALDADA, OPE_FECHA_ALTA, OPE_FECHA_VENCIMIENTO, OPE_TIPO_PRESTAMO,
				OPE_TIPO_CAMBIO, OPE_TASA_PRESTAMO, OPE_DESCUENTO_PREST, OPE_PLAZO, OPE_PORC_COMISION, OPE_PORC_IVA, OPE_IMPORTE_COMISION,
				OPE_IMPORTE_TOTAL, OPE_IMPORTE_PRIMA, OPE_PRECIO_PRESTAMO, OPE_PRECIO_PACTADA
			FROM OPE_C2
		), TAB_FINAL AS (
			SELECT CV.*, TAOP.*
			FROM CLIENTES_VIG CV
			LEFT JOIN TAB_OPE TAOP ON TAOP.OPE_CLI_CLAVE = CV.CLI_CLAVE
		) SELECT * FROM TAB_FINAL
 	""",
  	"SIMS":"""
  		WITH CLIENTES_ACTIVOS AS (
		    SELECT CLAVE, NOMBRE
		    FROM SIMS.SIMS_CONTRAPARTES 
		    WHERE NOMBRE NOT LIKE '%INACTI%' AND NOMBRE NOT LIKE '%APLICA%'
		), MOVIMIENTO AS (
		    SELECT SM.*, CAT.DESCRIPCION MOVIMIENTO
		    FROM SIMS.SIMS_MOVIMIENTOS SM
		    LEFT JOIN SIMS.SIMS_TIPOS_MOVTOS CAT ON CAT.CLAVE = SM.TIPO_MOVTO
		),  MOVIMIENTO_C2 AS (
		    SELECT SM.*, CAT.DESCRIPCION PORTAFOLIO
		    FROM MOVIMIENTO SM
		    LEFT JOIN SIMS.SIMS_TIPOS_PORTAFOLIOS CAT ON CAT.TIPO = SM.TIPO_PORTAFOLIO
		), MOVIMENTO_C3 AS (
			SELECT SM.*, CAT.DESCRIPCION VAR_MOVIMIENTO
		    FROM MOVIMIENTO_C2 SM
		    LEFT JOIN SIMS.SIMS_VARIANTES_MOVTOS CAT ON ( CAT.TIPO = SM.TIPO_MOVTO  AND CAT.CLAVE = SM.VARIANTE_MOVTO)
		), TAB_FINAL AS (
			SELECT CLAVE,NOMBRE,FOLIO,TIPO_MOVTO,MOVIMIENTO, TIPO_PORTAFOLIO, PORTAFOLIO, VARIANTE_MOVTO, VAR_MOVIMIENTO, FECHA_OPERACION,FECHA_VALOR,NUMERO_EMISION,
			FECHA_CUPON_ACTUAL,TASA,DIAS,PRECIO,VALOR_NOMINAL,VALOR_NOMINAL_AMORTIZADO,VALOR_COSTO,INTERESES_ACUMULADOS,
			MONTO_MOVIMIENTO,MONTO_VRR,VALOR_NOMINAL_DISPONIBLE,INTERESES_ANTICIPADOS,INTERESES_PROVISIONADOS,INTERESES_COMPLEMENTO,
			UTILIDAD,PERDIDA,FOLIO_COMPRA,SUBFOLIO_COMPRA,ESTATUS_MOVTO,TIPO_CAMBIO_COMPRA,TIPO_CAMBIO_VENTA,TITULOS_VENCIMIENTO,
			FECHA_LIQUIDA,NUMERO_TITULOS,PRECIO_SUCIO,FECHA_LIQUIDACION
			FROM CLIENTES_ACTIVOS AC
			LEFT JOIN MOVIMENTO_C3 MV ON MV.CLAVE_CONTRAPARTE = AC.CLAVE
		) SELECT * FROM TAB_FINAL
  	""",
    "SIPE": """
	 	WITH CLIENTES_ACTIVOS AS (
	 	    SELECT  BCO_CLAVE_FFON, BCO_CLAVE, BCO_NOMBRE, SPB.SUC_NUMERO
	 	    FROM SIPE.SIPE_BANCOS sp
	 	  	LEFT JOIN SIPE.SIPE_SUCURSALES_BANCO SPB ON SP.BCO_CLAVE = SPB.SUC_BCO_CLAVE
	 	    WHERE SP.BCO_ESTATUS = 'A'
	 	), CLI_CUENTAS_CONTRAPARTE AS (
	 		SELECT  CA.*, SCC.CIP_DIV_CLAVE, SCC.CIP_TES_CLAVE, SCC.CIP_SUC_NUMERO
	 		FROM CLIENTES_ACTIVOS CA
	 		LEFT JOIN SIPE.SIPE_CUENTAS_CONTRAPARTE SCC ON CA.SUC_NUMERO = SCC.CIP_SUC_NUMERO
	 	), CLI_INV_PRES AS (
	 		SELECT CCC.*, SIP.*
	 		FROM CLI_CUENTAS_CONTRAPARTE CCC
	 		LEFT JOIN SIPE.SIPE_INVERSIONES_PRESTAMOS SIP ON ( SIP.IPE_SUC_NUMERO = CCC.CIP_SUC_NUMERO AND SIP.IPE_TES_CLAVE = CCC.CIP_TES_CLAVE AND SIP.IPE_DIV_CLAVE = CCC.CIP_DIV_CLAVE )
	 	) SELECT * FROM CLI_INV_PRES
   		""",
    "SOI": """
		WITH CLIENTES_ACTIVOS AS (
		   SELECT  BA_BCO_FFON, BACVE_BANC, BANOM_BAN
		   FROM SOI.SOI_BANCO sb
		   WHERE BA_ACTIVO = 'S'
		), CLT_LINEA AS (
			SELECT CA.*, SBL.BLNO_LINEA
			FROM CLIENTES_ACTIVOS CA
			LEFT JOIN SOI.SOI_BANCO_LIN SBL ON CA.BACVE_BANC = SBL.BLCVE_BANC
		), LINEA_CT1 AS (
			SELECT SL.*, SB.TFDESC_CONT 
			FROM SOI.SOI_LINEA sl
			LEFT JOIN SOI.SOI_TIP_CREDI SB ON SL.LITIP_CONT = SB.TFTIP_CONT
		), CLT_LINEA_DESCRIP AS (
			SELECT CL.*, SL.*
			FROM CLT_LINEA CL 
			LEFT JOIN LINEA_CT1 SL ON CL.BLNO_LINEA = SL.LINO_LINEA
		) SELECT * FROM CLT_LINEA_DESCRIP
    	"""
}

list_dbs_clt_activos = [db_siag, db_sirac, db_tas, db_meca, db_sims, db_sipe, db_soi]
path_exit = "/home/ale1726/proyects/datalake/clientes/data/test/data/productos"
path_logs = "/home/ale1726/proyects/datalake/clientes/data/test/logs"
date_now = datetime.now().strftime("%d_%m_%Y") 


for database in list_dbs_clt_activos:
    try: 
        path_exit_temp = os.path.join(path_exit, database["NAME"], "data_origen", date_now)
        os.makedirs(path_exit_temp, exist_ok=True)
        get_table(path_exit = path_exit_temp , db = database, name_archivo = f"productos_clientes_{database['NAME']}", query  = querys_productos[database["NAME"]])  
    except Exception as error:
        path_exit_temp_log = os.path.join(path_exit, database["NAME"], "logs", date_now)
        os.makedirs(path_exit_temp_log, exist_ok=True)
        log_file =  os.path.join(path_exit_temp_log, f"errors_productos_{database['NAME']}_{date_now}.log")
        with open(log_file, 'a') as archivo:
            archivo.write(str(error))



"""            
query_sifc = 
	WITH CLIENTES_ACTIVOS AS (
		SELECT OID OID_CUSTOMERS, CUSTOMER_ID, LEGAL_NAME, DESCRIPTION, RFC, ADDRESS_DUMP 
		FROM SIFC.CUSTOMERS 
		WHERE CUSTOMER_STATUS = 'ACTIVE' 
	), CLIENTES_ACCOUNTS AS (
		SELECT CA.*, AC.OID OID_ACCOUNTS, AC.RFC RFC2
		FROM CLIENTES_ACTIVOS CA
		LEFT JOIN SIFC.ACCOUNTS AC ON CA.OID_CUSTOMERS = AC.CUSTOMER
	), CLIENTES_TRANS AS (
		SELECT CAC.*, "OID" ID_TRANSACTION, ENTRY_DATE FECHA_DE_ENTRADA, TA.ARRANGEMENT_DATE FECHA_DE_ACUERDO, 
		TA.SETTLEMENT_DATE FECHA_DE_LIQUIDACION, PRI_SERIES_AGREEDATE FECHA_DE_ACUERDO_SERIE_PRI, 
		SEC_SERIES_AGREEDATE FECHA_DE_ACUERDO_SERIE_SEC, TRANSACTION_END_DATE FECHA_DE_FIN_DE_TRANSACCION, 
		TRANSACTION_RATE TASA_DE_TRANSACCION, TX_COMMENTS COMENTARIOS_TX, TX_CONCEPT CONCEPTO_TX, 
		TRUST_GOAL OBJETIVO_DEL_FIDEICOMISO, TX_SUBTYPE SUBTIPO_TX, COMMISIONS_AMOUNT MONTO_DE_COMISIONES, 
		FUT_CLEAN_INTEREST INTERES_LIMPIO_FUTURO, USED_SURPLUS EXCEDENTE_UTILIZADO, DOLLARS_AMOUNT MONTO_EN_DOLARES, 
		DOLLARS_EX_RATE TASA_DE_CAMBIO_DOLARES, PRI_SERIES_AMOUNT MONTO_SERIE_PRI, GROSS_AMOUNT MONTO_BRUTO, 
		ORDERED_AMOUNT MONTO_ORDENADO
		FROM CLIENTES_ACCOUNTS CAC
		LEFT JOIN SIFC.TRANSACTIONS TA ON TA.PARTY_ACCOUNT = CAC.OID_ACCOUNTS
	), CLIENTES_DISP AS (
		SELECT CTR.*, PAYD."OID" ID_DISPERSION, PAYD.AMOUNT MONTO_DISPERSION, PAYD.BENEFICIARY_NAME NOMBRE_DE_BENEFICIARIO, PAYD.RFC RFC_BENEFICIARIO
		FROM CLIENTES_TRANS CTR
		LEFT JOIN SIFC.PAYMENT_DISPERSIONS PAYD ON PAYD."TRANSACTION" = CTR.ID_TRANSACTION
	) SELECT * FROM CLIENTES_DISP WHERE ID_TRANSACTION IS NOT NULL


try:
    path_exit_temp = os.path.join(path_exit, database["NAME"], "data_origen", date_now)
    os.makedirs(path_exit_temp, exist_ok=True)
    get_table("/home/ale1726/proyects/datalake/clientes/data/productos/SIFC", db_sifc, "productos_sifc", query=query_sifc)
except Exception as error:
        path_exit_temp_log = os.path.join(path_exit, database["NAME"], "logs", date_now)
        os.makedirs(path_exit_temp_log, exist_ok=True)
        log_file =  os.path.join(path_exit_temp_log, f"errors_productos_{database['NAME']}_{date_now}.log")
        with open(log_file, 'a') as archivo:
            archivo.write(str(error))



"""