
from tf import *
from db import *
from gd import * 
from datetime import datetime
import pandas as pd
from sqlalchemy import create_engine

sistema = ""
querys_productos ={
    "SIAG": """
    WITH CLIENTES_ACTIVOS AS (
		SELECT RESULTADO.*, INT.DESCRIPCION AS CLIENTE, INT.DESC_CORTA  
			FROM ( 
		    	SELECT *
		    	FROM GIA.GIA_GARANTIAS 
		    	WHERE ESTATUS_GARANTIA IS NULL OR ESTATUS_GARANTIA = 'R' AND (FECHA_VENCIMIENTO IS NULL)
				) RESULTADO
			INNER JOIN GIA.GIA_INTERMEDIARIOS INT ON RESULTADO.INTER_CLAVE = INT.CLAVE
		), CON_SUBPRODUCTOS AS(
			SELECT CA.*, SP.DESCRIPCION AS SUBPRODUCTO
			FROM CLIENTES_ACTIVOS CA
			LEFT JOIN GIA.SIAG_PORTAFOLIOS SP ON CA.CVE_CARTERA = SP.CVE_CARTERA AND CA.CVE_PORTAFOLIO = SP.CVE_PORTAFOLIO 
		), INFORMACION_GARANTIA AS (
			SELECT 
			CLAVE NUMERO_DE_GARANTIA,
			INTER_CLAVE NUMERO_CLIENTE,
			CLIENTE,
			DESC_CORTA,
			SUBPRODUCTO,
			FECHA_REGISTRO_GARANTIA,
			MONTO_CREDITO,
			PORCENTAJE_GARANTIZADO,
			MONTO_GARANTIZADO,
			TASA_INTERES,
			PORCENTAJE_COMISION,
			ROUND(MONTO_CREDITO * (PORCENTAJE_COMISION/100)) GANANCIA,
			EXTRACT(YEAR FROM FECHA_REGISTRO_GARANTIA) AIO,
			EXTRACT(MONTH FROM FECHA_REGISTRO_GARANTIA) MES,
			EXTRACT(DAY FROM FECHA_REGISTRO_GARANTIA) DIA
		  FROM CON_SUBPRODUCTOS
		) SELECT * FROM INFORMACION_GARANTIA
    """, 
    "SIRAC": """
        WITH CLT_ACT_X_CONTRATO AS (
        	SELECT cxc.CODIGO_CLIENTE, cxc.NUMERO_CONTRATO, c.FECHA_APERTURA, c.FECHA_VENCIMIENTO, c.MONTO_APROBADO, c.MONTO_DISPONIBLE, c.CODIGO_EMPRESA,
        	c.CODIGO_LINEA_FINANCIERA, c.OBSERVACIONES OB1, c.TIPO_CONTRATO, c.ESTADO_CONTRATO, c.CODIGO_SUB_APLICACION, c.CODIGO_APLICACION
            FROM SIRAC.PR_CONTRATOS_X_CLIENTE cxc
            INNER JOIN SIRAC.PR_CONTRATOS c ON cxc.NUMERO_CONTRATO = c.NUMERO_CONTRATO
            WHERE c.FECHA_VENCIMIENTO > SYSDATE AND ESTADO_CONTRATO = 1 
        ),  CLTS_ACT_LINEA_FINACIERA AS (
        	SELECT CAXC.*, LF.DESCRIPCION AS DESC_LINEA_FINANCIERA
        	FROM CLT_ACT_X_CONTRATO  CAXC
        	LEFT JOIN SIRAC.MG_LINEA_FINANCIERAS LF ON CAXC.CODIGO_LINEA_FINANCIERA = LF.CODIGO_LINEA_FINANCIERA AND CAXC.CODIGO_EMPRESA = LF.CODIGO_EMPRESA
        ), CLT_CONTRATO_PRESTAMOS AS (
        	SELECT CALF.*, PP.NUMERO_PRESTAMO, PP.CODIGO_ESTADO_CARTERA, PP.ESTADO, PP.CODIGO_TIPO_AMORTIZACION, PP.MONTO_INICIAL, 
        	PP.VALOR_CUOTA, PP.TIPO_TASA, PP.TASA_TOTAL, PP.PLAZO, PP.NUMERO_CUOTAS, PP.COMISION, PP.CANTIDAD_CUOTAS_PAGADAS
        	FROM CLTS_ACT_LINEA_FINACIERA CALF
        	LEFT JOIN SIRAC.PR_PRESTAMOS PP ON CALF.CODIGO_CLIENTE = PP.CODIGO_CLIENTE AND CALF.NUMERO_CONTRATO = PP.NUMERO_CONTRATO
        ), CLTS_ACTIVOS_FILTRO_2 AS(
        	SELECT * FROM CLT_CONTRATO_PRESTAMOS WHERE ESTADO = 1 OR ESTADO = 10 OR ESTADO IS NULL
        ), CLT_SUP_APLICACION AS (
        	SELECT CAF2.*, MGSA.DESCRIPCION PRODUCTO, MGSA.CODIGO_MONEDA
        	FROM CLTS_ACTIVOS_FILTRO_2 CAF2
        	LEFT JOIN SIRAC.MG_SUB_APLICACIONES MGSA ON CAF2.CODIGO_APLICACION = MGSA.CODIGO_APLICACION AND CAF2.CODIGO_SUB_APLICACION = MGSA.CODIGO_SUB_APLICACION
        ), CLT_TIPOS_AMORTIZACION AS (
        	SELECT CSA.*, PRTA.DESCRIPCION AS AMORTIZACION 
        	FROM CLT_SUP_APLICACION CSA
        	LEFT JOIN SIRAC.PR_TIPOS_AMORTIZACION PRTA ON CSA.CODIGO_TIPO_AMORTIZACION = PRTA.CODIGO_TIPO_AMORTIZACION
        ), CLT_INFO_X_CONTRATO AS (
        	SELECT CTTAM.*, MG.CODIGO_TIPO_IDENTIFICACION, MG.CODIGO_PAIS, NOMBRES,
        	PRIMER_APELLIDO,SEGUNDO_APELLIDO,SEXO,FECHA_DE_NACIMIENTO,
        	RAZON_SOCIAL,NOMBRE_COMERCIAL,ESTATUTO,CODIGO_DEPARTAMENTO,
        	CODIGO_MUNICIPIO,NO_EMPLEADOS,VENTAS_NETAS,CODIGO_SECTOR,
        	CODIGO_SUBSECTOR,CODIGO_RAMA,CODIGO_CLASE,PAIS_NACIMIENTO
        	FROM CLT_TIPOS_AMORTIZACION CTTAM
        	LEFT JOIN SIRAC.MG_CLIENTES MG ON MG.CODIGO_CLIENTE = CTTAM.CODIGO_CLIENTE
        ), CLT_INFO_P AS (
        	SELECT CIXC.*, x.NOMBRE PAIS, x.NACIONALIDAD
        	FROM CLT_INFO_X_CONTRATO CIXC
        	LEFT JOIN SIRAC.MG_PAISES x ON CIXC.CODIGO_PAIS = x.CODIGO_PAIS
        ), CLT_INFO_MUN AS (
        	SELECT CIP.*, MM.NOMBRE DELEGACION_MUNICIPIO      
        	FROM CLT_INFO_P CIP
        	LEFT JOIN SIRAC.MG_MUNICIPIOS MM ON  MM.CODIGO_PAIS = CIP.CODIGO_PAIS AND MM.CODIGO_DEPARTAMENTO = CIP.CODIGO_DEPARTAMENTO AND MM.CODIGO_MUNICIPIO = CIP.CODIGO_MUNICIPIO
        ), CLT_INFO_ENT_FED AS (
            SELECT 
                CIM.*, MD.NOMBRE AS ENTIDAD_FEDERATIVA     
            FROM CLT_INFO_MUN CIM
            LEFT JOIN SIRAC.MG_DEPARTAMENTOS MD ON  MD.CODIGO_PAIS = CIM.CODIGO_PAIS AND MD.CODIGO_DEPARTAMENTO = CIM.CODIGO_DEPARTAMENTO
        ), CLT_INF_SECTOR AS(
        	SELECT CIEF.*, MTS.DESCRIPCION TIPO_SECTOR
        	FROM CLT_INFO_ENT_FED CIEF
        	LEFT JOIN SIRAC.MG_TIPO_SECTOR MTS ON CIEF.CODIGO_SECTOR =  MTS.CODIGO_SECTOR
        ), CLT_INF_SUBSECTOR AS(
        	SELECT CISEC.*, MTSC.DESCRIPCION TIPO_SUBSECTOR
        	FROM CLT_INF_SECTOR CISEC
        	LEFT JOIN SIRAC.MG_TIPO_SUBSECTOR MTSC ON CISEC.CODIGO_SECTOR = MTSC.CODIGO_SECTOR AND CISEC.CODIGO_SUBSECTOR = MTSC.CODIGO_SUBSECTOR
        ), CLT_INF_RAMA AS (
        	SELECT CISECS.*, MTR.DESCRIPCION TIPO_RAMA
        	FROM CLT_INF_SUBSECTOR CISECS
        	LEFT JOIN SIRAC.MG_TIPO_RAMA MTR ON 
        	CISECS.CODIGO_SECTOR = MTR.CODIGO_SECTOR AND CISECS.CODIGO_SUBSECTOR = MTR.CODIGO_SUBSECTOR  
        	AND CISECS.CODIGO_RAMA = MTR.CODIGO_RAMA
        ), CLT_INF_CLASE AS (
        	SELECT CIRA.*, MTC.DESCRIPCION TIPO_CLASE
        	FROM CLT_INF_RAMA CIRA
        	LEFT JOIN SIRAC.MG_TIPO_CLASE MTC ON 
        	CIRA.CODIGO_SECTOR = MTC.CODIGO_SECTOR AND CIRA.CODIGO_SUBSECTOR = MTC.CODIGO_SUBSECTOR  
        	AND CIRA.CODIGO_RAMA = MTC.CODIGO_RAMA AND CIRA.CODIGO_CLASE = MTC.CODIGO_CLASE
        ), TAB_FINAL_CLIENTE_PROD AS (
        	SELECT
        	CODIGO_CLIENTE,
        	CODIGO_TIPO_IDENTIFICACION,
        	NOMBRES,
        	PRIMER_APELLIDO,
        	SEGUNDO_APELLIDO,
        	SEXO,
        	FECHA_DE_NACIMIENTO,
        	RAZON_SOCIAL,
        	NOMBRE_COMERCIAL,
        	NO_EMPLEADOS,
        	VENTAS_NETAS,
        	PAIS,
        	NACIONALIDAD,
        	DELEGACION_MUNICIPIO,
        	ENTIDAD_FEDERATIVA,
        	TIPO_SECTOR,
        	TIPO_SUBSECTOR,
        	TIPO_RAMA,
         	TIPO_CLASE,
        	NUMERO_CONTRATO,
        	NUMERO_PRESTAMO,
        	FECHA_APERTURA,
        	EXTRACT(YEAR FROM FECHA_APERTURA) "AÑO_REGISTRO",
        	EXTRACT(MONTH FROM FECHA_APERTURA) MES_REGISTRO,
        	EXTRACT(DAY FROM FECHA_APERTURA) DIA_REGISTRO,
        	FECHA_VENCIMIENTO,
        	EXTRACT(YEAR FROM FECHA_VENCIMIENTO) "AÑO_VENCIMIENTO",
        	EXTRACT(MONTH FROM FECHA_VENCIMIENTO) MES_VENCIMIENTO,
        	EXTRACT(DAY FROM FECHA_VENCIMIENTO) DIA_VENCIMIENTO,
        	PRODUCTO,
        	DESC_LINEA_FINANCIERA,
        	CODIGO_MONEDA,
        	MONTO_APROBADO,
        	MONTO_DISPONIBLE,
        	MONTO_INICIAL,
        	TIPO_TASA,
        	TASA_TOTAL,
        	PLAZO,
        	CODIGO_TIPO_AMORTIZACION,
        	AMORTIZACION,
        	NUMERO_CUOTAS, 
        	VALOR_CUOTA,
        	CANTIDAD_CUOTAS_PAGADAS
        	FROM CLT_INF_CLASE
        	ORDER BY CODIGO_CLIENTE
        ) SELECT * FROM TAB_FINAL_CLIENTE_PROD
        """,
    "TAS": """
        WITH CLIENTES_ACTIVOS AS(
			SELECT CUENTA, ESPROVEED, TIPINVE, NLINEA, NOMBRE, NOMLARGO, RFC 
		    FROM TAS.CLIENTE cl
		    WHERE cl.FBAJA IS NULL
		), CLIENTES_ACT_TP AS (
			SELECT CA.*, TI.DESCRIP
			FROM CLIENTES_ACTIVOS CA
			LEFT JOIN TAS.TIPINVER TI ON TI.U##TIPINVE =  CA.TIPINVE
		), CLIENTES_OPERACIONES AS (
			SELECT CAT.*, 
			FO.ICONTRATO, FO.IORDEN, FO.FOPER, FO.FLIQ, FO.CPZO_DE, FO.CPZO_A, FO.FVENCE,  
			FO.IINSTR, FO.ITINSTR, FO.TASA, FO."U##ITAJUS",
			FO.MORDEN, FO.MASIG, FO.FECHA, FO.MREAL, FO.PLAZOREF
			FROM CLIENTES_ACT_TP CAT
			LEFT JOIN TAS.FORDEN FO ON FO.ICONTRATO = CAT.CUENTA
		), CLIENTES_OPERACIONES_INST AS (
			SELECT CO.*, FT.NTINSTR
			FROM CLIENTES_OPERACIONES CO
			LEFT JOIN TAS.FTINSTR FT ON FT."U##ITINSTR" = CO.ITINSTR 
		), TAB_FINAL AS ( 
			SELECT 
			CUENTA NUMERO_CLIENTE,
			ESPROVEED,
			DESCRIP TIPO_PERSONA, 
			NOMBRE, 
			NOMLARGO, 
			RFC, 
			NLINEA,
			ICONTRATO,
			IORDEN,
			FOPER,
			EXTRACT(YEAR FROM FOPER) "ANIO_OPE",
			EXTRACT(MONTH FROM FOPER) "MES_OPE",
			EXTRACT(DAY FROM FOPER) "DIA_OPE",
			FLIQ,
			EXTRACT(YEAR FROM FLIQ) "ANIO_FLIQ",
			EXTRACT(MONTH FROM FLIQ) "MES_FLIQ",
			EXTRACT(DAY FROM FLIQ) "DIA_FLIQ",
			CPZO_DE,
			CPZO_A,
			PLAZOREF,
			FVENCE,
			EXTRACT(YEAR FROM FVENCE) "ANIO_FVENCE",
			EXTRACT(MONTH FROM FVENCE) "MES_FVENCE",
			EXTRACT(DAY FROM FVENCE) "DIA_FVENCE",
			IINSTR,
			ITINSTR,
			NTINSTR,
			TASA,
			"U##ITAJUS" MONEDA,
			MORDEN MONTO_ORDEN,
			MASIG MONTO_ASIGNADO,
			MREAL MONTO_REAL,
			FECHA FECHA_REGISTRO
			FROM CLIENTES_OPERACIONES_INST 
			WHERE IORDEN IS NOT NULL
			) SELECT * FROM TAB_FINAL
		""",
}

list_dbs_clt_activos = [db_siag, db_sirac, db_tas]
path_exit = "/home/ale1726/proyects/datalake/clientes/data/productos"
path_logs = "/home/ale1726/proyects/datalake/clientes/data/productos/logs"
date_now = datetime.now().strftime("%d_%m_%Y") 


for database in list_dbs_clt_activos:
    try: 
        path_exit_temp = os.path.join(path_exit, database["NAME"], "data_origen", date_now)
        os.makedirs(path_exit_temp, exist_ok=True)
        get_table(path_exit = path_exit_temp , db = database, name_archivo = f"productos_clientes_{database['NAME']}", query  = querys_productos[database["NAME"]])  
    except Exception as error:
        path_exit_temp_log = os.path.join(path_exit, database["NAME"], "logs", date_now)
        os.makedirs(path_exit_temp_log, exist_ok=True)
        log_file =  os.path.join(path_exit_temp_log, f"errors_productos_{database['NAME']}_{date_now}.log")
        with open(log_file, 'a') as archivo:
            archivo.write(str(error))



"""            
query_sifc = 
	WITH CLIENTES_ACTIVOS AS (
		SELECT OID OID_CUSTOMERS, CUSTOMER_ID, LEGAL_NAME, DESCRIPTION, RFC, ADDRESS_DUMP 
		FROM SIFC.CUSTOMERS 
		WHERE CUSTOMER_STATUS = 'ACTIVE' 
	), CLIENTES_ACCOUNTS AS (
		SELECT CA.*, AC.OID OID_ACCOUNTS, AC.RFC RFC2
		FROM CLIENTES_ACTIVOS CA
		LEFT JOIN SIFC.ACCOUNTS AC ON CA.OID_CUSTOMERS = AC.CUSTOMER
	), CLIENTES_TRANS AS (
		SELECT CAC.*, "OID" ID_TRANSACTION, ENTRY_DATE FECHA_DE_ENTRADA, TA.ARRANGEMENT_DATE FECHA_DE_ACUERDO, 
		TA.SETTLEMENT_DATE FECHA_DE_LIQUIDACION, PRI_SERIES_AGREEDATE FECHA_DE_ACUERDO_SERIE_PRI, 
		SEC_SERIES_AGREEDATE FECHA_DE_ACUERDO_SERIE_SEC, TRANSACTION_END_DATE FECHA_DE_FIN_DE_TRANSACCION, 
		TRANSACTION_RATE TASA_DE_TRANSACCION, TX_COMMENTS COMENTARIOS_TX, TX_CONCEPT CONCEPTO_TX, 
		TRUST_GOAL OBJETIVO_DEL_FIDEICOMISO, TX_SUBTYPE SUBTIPO_TX, COMMISIONS_AMOUNT MONTO_DE_COMISIONES, 
		FUT_CLEAN_INTEREST INTERES_LIMPIO_FUTURO, USED_SURPLUS EXCEDENTE_UTILIZADO, DOLLARS_AMOUNT MONTO_EN_DOLARES, 
		DOLLARS_EX_RATE TASA_DE_CAMBIO_DOLARES, PRI_SERIES_AMOUNT MONTO_SERIE_PRI, GROSS_AMOUNT MONTO_BRUTO, 
		ORDERED_AMOUNT MONTO_ORDENADO
		FROM CLIENTES_ACCOUNTS CAC
		LEFT JOIN SIFC.TRANSACTIONS TA ON TA.PARTY_ACCOUNT = CAC.OID_ACCOUNTS
	), CLIENTES_DISP AS (
		SELECT CTR.*, PAYD."OID" ID_DISPERSION, PAYD.AMOUNT MONTO_DISPERSION, PAYD.BENEFICIARY_NAME NOMBRE_DE_BENEFICIARIO, PAYD.RFC RFC_BENEFICIARIO
		FROM CLIENTES_TRANS CTR
		LEFT JOIN SIFC.PAYMENT_DISPERSIONS PAYD ON PAYD."TRANSACTION" = CTR.ID_TRANSACTION
	) SELECT * FROM CLIENTES_DISP WHERE ID_TRANSACTION IS NOT NULL


try:
    path_exit_temp = os.path.join(path_exit, database["NAME"], "data_origen", date_now)
    os.makedirs(path_exit_temp, exist_ok=True)
    get_table("/home/ale1726/proyects/datalake/clientes/data/productos/SIFC", db_sifc, "productos_sifc", query=query_sifc)
except Exception as error:
        path_exit_temp_log = os.path.join(path_exit, database["NAME"], "logs", date_now)
        os.makedirs(path_exit_temp_log, exist_ok=True)
        log_file =  os.path.join(path_exit_temp_log, f"errors_productos_{database['NAME']}_{date_now}.log")
        with open(log_file, 'a') as archivo:
            archivo.write(str(error))



"""